spring:
    jmx:
        enabled: false
    datasource:
            name: blueprint
            url: jdbc:mysql://127.0.0.1:3307/music_sys?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
            username: root
            password: 123456
            type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            filters: stat
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: cn.will.po

javafx:
    title: Blueprint
    stage:
      style: undecorated
